#! /bin/bash	
# the main read function to ignor special cases and make sure the name contains only
# upper , lower case char , num , spaces and {_,-} only

custom_read(){

	set -o noglob
		
	read -r "$@" readout
	
if [[ $readout =~ ^[a-zA-Z0-9_[:space:].@-]*$ ]] ; then

	set +o noglob

	return 0
	
else

	echo -e "${RED} your input is not valid be serious${ENDCOLOR} "
			
	return 102
		
fi
	}
