#!/usr/bin/bash
show_menu() {
    local menu_headline="$;;;;;;;;$1;;;;;;;;"
    local lines=$(echo -e "$menu_headline" |add_lines '=')
    echo -e "${LIGHTBLUE}${lines}${ENDCOLOR}"
    echo -e "${LIGHTBLUE};;;;;;;;${ENDCOLOR}${GREEN}$1${ENDCOLOR}${LIGHTBLUE};;;;;;;;${ENDCOLOR}"
    echo -e "${LIGHTBLUE}${lines}${ENDCOLOR}"
    local i=1
    echo -e "${GREEN}Select one of the Following options${ENDCOLOR}"
    echo -e "${BLUE}-----------------------------------${ENDCOLOR}"
    for option in "${@:2}";do
        echo -e "$i. ${YELLOW} $option ${ENDCOLOR}"
        echo -e "${BLUE}----------${ENDCOLOR}"
        ((++i))
    done
    echo -e "${LIGHTBLUE}==========================================${ENDCOLOR}"
}
