#! /usr/bin/bash
COLUMN_DELIMITER=:
COLUMN_INFO_DELIMITER=,

load_metadata() {
: '
	this function loads metadata of the required table
'
	echo $( head -n 1 $TABLE )
}

getprimarykeycolumn() {
    : '
        this function get the column number of the primary key column
        $1 is the supplied metadata of the TABLE
    '
	echo "$1" | tr "$COLUMN_DELIMITER" "\n"| grep -ne ',pk$' | cut -d':' -f1  
}

load_column(){
	tail -n +2 $TABLE |cut -d$COLUMN_DELIMITER -f $1 
}

load_column_info(){
    echo "$1" | cut -d"$COLUMN_DELIMITER" -f $2 |\
		cut -d"$COLUMN_INFO_DELIMITER" -f 1,2,3 --output-delimiter=' '
}
get_columns_names() {
    cut -d "$COLUMN_DELIMITER" --fields=$1 | sed -e 's/,[,a-zA-Z]*:/ /g' -e 's/,.*$//g' -e 's/ /,/g'
}
select_data() {
    : ' 
    $1 is the selected columns numbers passed as 1,2,3,4,.....
    $2 is the selected  table rows passed as 1,2,3,4,.... 
    '
    [ -n "${2}" ] && programtext="$(echo NR==${2//,/' || NR=='})"
	load_column $1 |awk "$programtext"
}