#!/bin/bash

source ../modules/custom_read
source ../modules/colorcodes
custom_read -p "enter database name`echo $'\n> '`" || return $?
db=$readout
connect_database(){

	if [ -d "$1" ] ; then
		cd "$1"
	else
		printf "${RED}this name dosent exist .. sorry\n${ENDCOLOR}"
		return 99
		fi
}
connect_database $db
