#! /bin/bash

# source the custom_read function

source check_meta_data
source modules/custom_read

# run the function to read the table name to create


#function that create a table
function create_table(){
	
	touch "$1"
	
	}

# check if the file is exist return error msg or go and create the table

function check_and_create() {

	
	if [[ -f "$1" ]] ; then
	
		echo "this table already exist"
		
	elif [[ $1 =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] ; then
	
		create_table "$1"
		
		echo "$1"	
		
	else
	
		echo " be serious enter a valid name ^-^ "
	
	fi
}
	
custom_read $readout && check_and_create $readout

#when the user successfully created the table run this function to asign his columns

read -p "enter the number of columns to your table : " column_num

column_meta_data $column_num $readout

