#! /bin/bash
source $(dirname $0)/modules/custom_read
source $(dirname $0)/modules/colorcodes

function check_and_create() {
	custom_read -p "enter database name : " || return $?
	if [[ -d "$readout" ]] ; then
	
		echo "this database already exist"
		return 123
		
	elif [[ $readout =~ ^[a-zA-Z][a-zA-Z0-9_]*$ ]] && [ "$(echo $readout|wc -c)" -le 63 ] ; then
	
		create_database "$readout"
		
		echo "Database $readout has been created successfully"
		return 0

	else
		echo "This Database Name is not valid "
        return 122
	
	fi
}

create_database() {
	mkdir "$1"
}
check_and_create