#! /bin/bash



source modules/custom_read

#take the input to check if its exist to delete or not exist

custom_read

# function to delete data_base if its exist :

function delete_database() {
	#if the dir id esist :	
	
	if [[ -d $1 ]]; then
		rm -rf data/$1
	else 
		#if there is no directory return error code :
		echo " there is no database with this name "
		return 101
	fi
}

delete_database $readout
