#!/bin/bash

source $(dirname $0)/modules/querytable
source $(dirname $0)/modules/checks
source $(dirname $0)/modules/where
source $(dirname $0)/modules/formats
source $(dirname $0)/modules/colorcodes
source $(dirname $0)/modules/custom_read
source $(dirname $0)/modules/menu


function gathering(){

custom_read -p "Please enter the Table name : " || return $?

chk_table_name $readout || return $?

TABLE=$readout
METADATA=$(load_metadata)

}
get_target_rows(){
      variable={}
      local RowsOfCondition
      RowsOfCondition=$(where_fn $COLUMN_NO $CONDITION "$INPUT") || { RC=$? ; echo $RowsOfCondition ; return $RC ; }
      variable=$(echo "$RowsOfCondition" | increment_fn | tr '\n' ' ')
}


delete_row() {
     
      declare row_number="${@:1:$#-1}"
      local filename=${@: -1}
   	
    # Delete the specified row using sed

    [ -n "$row_number" ] && sed -i "${row_number// /d;}d" "${filename}"
	echo $row_number
    echo "you rows have been deleted from : ${filename}."

}

gathering && where_menu && get_target_rows && delete_row $variable $TABLE
