#!/bin/bash

source $(dirname $0)/modules/querytable
source $(dirname $0)/modules/checks
source $(dirname $0)/modules/where
source $(dirname $0)/modules/formats
source $(dirname $0)/modules/colorcodes
source $(dirname $0)/modules/custom_read
source $(dirname $0)/modules/menu


function gathering(){

custom_read -p "Please enter the Table name : " || return $?

chk_table_name $readout || return $?

TABLE=$readout
METADATA=$(load_metadata)

}
get_rows(){
	local RowsOfCondition
	
      RowsOfCondition=$(where_fn $COLUMN_NO $CONDITION "$INPUT")
      RowsOfCondition=$(echo "$RowsOfCondition" | tr '\n' ' ')
      local RC=$? 
      [ $RC -eq 0 ] && [ -n "$RowsOfCondition" ] && variable=$(echo "$RowsOfCondition" | increment_fn) || { echo $RowsOfCondition; return $RC; }
      echo $RowsOfCondition
}

delete_row() {
     
      declare -a row_number="${@:1:$#-1}"
      local filename=${@: -1}
   	
    # Delete the specified row using sed

    [ -n "$row_number" ] && sed -i "${row_number// /d;}d" "${filename}"

    echo "Row ${row_number} deleted from ${filename}."

}

# Example usage: delete row 3 from tabl
gathering && where_menu && get_rows && delete_row $variable $TABLE
