#! /bin/bash

#read the db name and take the input to "db_name"

read -r -p "Enter the db name : " db_name

# function to delete data_base if its exist :

function delete_db_table() {

	#if the dir id esist :	
	
   if [[ -d $1 ]]; then
   
   rm -rf data/$1
   
   else 
   	#if there is no directory return error code :
   	
   	echo " there is no database with this name "
   	
   	return 101
   	
   	fi
}

delete_db_table $db_name
