#! /usr/bin/bash
source modules/check_meta_data 
source modules/checks 
source modules/colorcodes 
source modules/custom_read 
source modules/formats 
source modules/menu 
source modules/querytable 
source modules/where
[ -d data ] || mkdir data 
cd data/
clear
#tput cup 30 0

DDL_menu() {
    show_menu "Welcome to our DBMS_BASH" "Create Database" "Drop Database" "Connect to Database" "List Databases" "QUIT"
    while [ 1 -eq 1 ]; do
        custom_read -p ">>" && case ${readout,,} in 
            "1"|"create")
                bash ../create_database
            ;;
            "2"|"drop"|"delete"|"remove")
                bash ../delete_database
            ;;
            "3"|"connect")
                #source ../connect_to_database
                source ../connect \
                && { DML_menu
                cd ..
                show_menu "Welcome to our DBMS_BASH" "Create Database" "Drop Database" "Connect to Database" "List Databases" "QUIT"
                }
            ;;
            "4"|"list"|"ls")
                ls  --file-type . | grep "/" |tr -d "/" 
            ;;
            "5"|"quit"|"exit"})
                echo GoodBye
                break
            ;;
            *) 
            echo -e "${RED}Please enter a correct input${ENDCOLOR}"
            ;;
        esac
    done
}
DML_menu() {
local DATABASE=$(pwd|sed "s|^.*/||g")
    show_menu "Welcome To Database $DATABASE" "Create TABLE" "Drop TABLE" "Delete Table" "Select" "list Tables" "Insert into table" "Update table" "Truncate Table" "disconnect from database" "quit"
    while [ 1 -eq 1 ]; do
        custom_read -p ">>" && case ${readout,,} in 
            "1"|"create")
                bash ../../create_table
            ;;
            "2"|"drop")
                echo "dropping"
            ;;
            "3"|"delete")
                echo deleting
            ;;
            "4"|"select"|"ls")
                bash ../../select
            ;;
            "5"|"list"|"ls")
                ls --file-type . | grep -v "/|@"
            ;;
            "6"|"insert")
                bash ../../insert && echo -e "The Data has been inserted ${GREEN}sucessfully${ENDCOLOR}"
            ;;
            "7"|"update")
                echo "Updating"
            ;;
            "8"|"truncate")
                echo "truncating"
            ;;
            "9"|"disconnect")
                echo -e "${MAGENTA}disconnecting${ENDCOLOR}"
                break
            ;;
            "0"|"quit"|"exit")
                echo -e "${MAGENTA}GOODBYE${ENDCOLOR}"
                exit 0
            ;;
            *) 
            echo -e "${RED}Please enter a correct input${ENDCOLOR}"
            ;;
        esac
    done
}

DDL_menu