#! /usr/bin/bash
source $(dirname $0)/modules/querytable
source $(dirname $0)/modules/checks
source $(dirname $0)/modules/where
source $(dirname $0)/modules/formats
source $(dirname $0)/modules/colorcodes
source $(dirname $0)/modules/custom_read
source $(dirname $0)/modules/menu
# TABLE=data/database1/test1
# COLUMN_NO=1
# CONDITION=""
# INPUT='whatever'
# declare COLUMN_INFO=($( load_column_info $(load_metadata) $COLUMN_NO ))
select_data_entry() {
    custom_read -p "Please enter the Table name : " || return $?
    chk_table_name $readout || return $?
    TABLE=$readout 
    METADATA=$(load_metadata)
    echo "which columns u select, enter their names or numbers with spaces"
    custom_read -p ">>" || return $?
    declare -a SELECT_COLUMN_NO_temp
    for i in $readout;do
        if ( [[ $i =~ ^[1-9][0-9]*$ ]] && [ $i -le $(get_max_columns_no $METADATA ) ] ); then
            SELECT_COLUMN_NO_temp+=($i)
        elif [[ $readout =~ ^[_a-z] ]];then
            SELECT_COLUMN_NO_temp+=($(echo -n "$METADATA" | Get_column_number_from_name $i))
        else
            echo -e "${RED}Please enter a correct input${ENDCOLOR}"
            return 143
        fi
    done
    [ -n "${SELECT_COLUMN_NO_temp}" ] && SELECT_COLUMN_NO=$(echo ${SELECT_COLUMN_NO_temp[@]}|tr " " "\n"|sort|uniq|Format_fn)
}

select_fn() {
    local ROWSNUMBER
    ROWSNUMBER=$(where_fn $COLUMN_NO $CONDITION "$INPUT")
    RC1=$?
    [[ 0 -eq $RC1 ]] && ROWSNUMBER=$(Format_fn $ROWSNUMBER) || { echo $ROWSNUMBER;  return $RC1; }
    select_data $SELECT_COLUMN_NO $ROWSNUMBER | view_table $(load_metadata | get_columns_names $SELECT_COLUMN_NO) || return $?
}

select_data_entry &&  where_menu &&  select_fn 



