#! /usr/bin/bash
source $(dirname $0)/modules/querytable
source $(dirname $0)/modules/checks
source $(dirname $0)/modules/where
source $(dirname $0)/modules/formats


TABLE=data/database1/test1
COLUMN_NO=1
CONDITION=""
INPUT='whatever'
declare COLUMN_INFO=($( load_column_info $(load_metadata) $COLUMN_NO ))
#where_fn $COLUMN_NO $CONDITION $INPUT

#  seq -s_ 32|tr -d '[:digit:]';tail -n +2 data/database1/table1|sed 's/$/:/'|column -ts : -o "|" -N name,number,birthdate |sed -e 's/^/|/' 
# ;seq -s― 32|tr -d '[:digit:]'

select_fn() {
    local ROWSNUMBER
    ROWSNUMBER=$(where_fn $COLUMN_NO $CONDITION "$INPUT")
    RC1=$?
    #increment_fn 
    [[ 0 -eq $RC1 ]] && ROWSNUMBER=$(Format_fn $ROWSNUMBER) || { echo $ROWSNUMBER;  return $RC1; }
    select_data $1 $ROWSNUMBER | view_table $(load_metadata | get_columns_names $1) || return $?
}
select_fn 1,2,3
#where_fn $COLUMN_NO $CONDITION $INPUT
#TextWhereOperation "$COLUMN_NO" "$CONDITION" "$INPUT"
